###############################################################################
# FOR PIGEONPOSSE USAGE
###############################################################################

web:
  
  - id: "clippo"
    name: "clippo"
    type: "library"
    subtypes:
      - Bin
      - CLI
      - Node
    version: "{{package.version}}"
    description: "{{package.description}}"
    homepage: "{{package.homepage}}"
    repo: "{{package.repository.url}}"
    license: "{{package.extra.licenseUrl}}"
    logo: "https://raw.githubusercontent.com/pigeonposse/{{package.name}}/main/docs/public/logo.png"
    banner: "https://raw.githubusercontent.com/pigeonposse/{{package.name}}/main/docs/public/banner.png"
    status: "active"

###############################################################################
