###############################################################################
# DEPLOY DOCS WEB TO CLOUDFLARE
###############################################################################

name: 📖 Deploy docs 

###############################################################################
# ON
###############################################################################

on:
  workflow_dispatch:
concurrency: ${{ github.workflow }}-${{ github.ref }}
env:
    GITHUB_TOKEN: ${{ github.token }}

###############################################################################
# JOBS
###############################################################################

jobs:
  deploy:
    name: Deploy documentation web
    runs-on: ubuntu-latest
    steps:

      #########################################################################
      # INIT & BUILD PKG
      #########################################################################

      - name: ⬇️🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.12.1
      - name: ⬇️🛎 Checkout
        uses: actions/checkout@v4
      - name: ⬇️🥡 Install pnpm
        uses: pnpm/action-setup@v4
      - name: ⬇️🟢 Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: ⬇️📦 Install pkg dependencies
        run: pnpm install --no-frozen-lockfile

      ###################################################################
      # BUILD AND DEPLOY
      ###################################################################

      - name: 🏗 Build package
        run: pnpm doc build

      - name: 🌥 Deploy in cloudflare pages
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          projectName: "clippo"
          directory: 'packages/docs/dist'
          wranglerVersion: '3'
